plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - SUMMARY.md
  - preface.md
  - translate.md
  - ch1.md
  - ch2.md
  - ch3.md
  - ch4.md
  - ch5.md
  - reference.md

remove_theme: sighingnow/jekyll-gitbook
